
GP_CHIP := GP712

obj-m += greenpeak_$(GP_CHIP)_drv.o
ccflags-y                       += -DGP712

greenpeak_$(GP_CHIP)_drv-objs :=    gpCore.o \
                                gpIo.o    \
                                gpSpi.o   \







